; PlatformIO Project Configuration File

[platformio]
build_dir = C:/Users/User2/.pio-build/stm32_nod

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
lib_deps =
  https://github.com/simplefoc/Arduino-FOC.git#v2.3.5

lib_archive = false

;lib_extra_dirs =
;  C:/Users/User2/Documents/Vetőgép/agopen-rate-can-ecu/firmware/stm32g-node/simplefoc_poc/.pio/libdeps/genericSTM32G431CB

;lib_deps =
;  askuric/Simple FOC@^2.2
