; Simple STM32G431 6PWM motor controller with cyclic CAN status.

[platformio]
build_dir = C:/pio_build/stm32_6pwm_can_simple
libdeps_dir = C:/pio_libdeps/stm32_6pwm_can_simple

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
lib_deps =
  askuric/Simple FOC@2.3.5
lib_archive = false
build_flags =
  -DHAL_FDCAN_MODULE_ENABLED
