[platformio]
build_dir = C:/pio_build/simplefoc_minimal_3pwm

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
lib_extra_dirs =
  C:/Users/User2/Documents/Vetőgép/agopen-rate-can-ecu/firmware/stm32g-node/simplefoc_poc/.pio/libdeps/genericSTM32G431CB
