[platformio]
build_dir = C:/pio_build/simplefoc_poc

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
lib_deps =
  https://github.com/simplefoc/Arduino-FOC.git#v2.3.5

build_flags =
  -D HAL_FDCAN_MODULE_ENABLED
